name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - uses: actions/checkout@v3
    - name: Create a Release
      run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        INPUT_TITLE: ${{ steps.get_version.outputs.VERSION }}
